### PR TITLE
Allow to use any magento installer version

### PR DESCRIPTION
**Pull request by ihor-sviziev**
When I'm tried to install this module - I got dependence error:
```
   Problem 1
     - onepica/avatax 2.6.3-stable requires magento-hackathon/magento-composer-installer dev-master -> no matching package found.
     - onepica/avatax 2.6.3-stable requires magento-hackathon/magento-composer-installer dev-master -> no matching package found.
     - onepica/avatax 2.6.3-stable requires magento-hackathon/magento-composer-installer dev-master -> no matching package found.
     - Installation request for onepica/avatax 2.6.3 -> satisfiable by onepica/avatax[2.6.3-stable].```

To fix this issue this module should depends ANY magento composer installer version.

### CODE REVIEW

**Comment by rredko-sysiq** [comment]
Will be added to 2.6.5 release

**Comment by ihor-sviziev** [comment]
@rredko-sysiq looks like you missed my commin in 2.6.5 release

**Comment by rredko-sysiq** [comment]
@ihor-sviziev, this change caused problems with deployment to our environments. As far as we had limited time to release new version we reverted this change. But your issue looks reasonable, so we will proceed with investigation and i think fix in further releases.

**Comment by ihor-sviziev** [comment]
@rredko-sysiq maybe we should reopen this issue? Which issues do you seen? Maybe I can help you to resolve them?

**Comment by ihor-sviziev** [comment]
@rredko-sysiq any reasons to prevent using of stable composer installer version?

**Pull request closed without merging**
